#!/bin/bash

#
# a facade for getprop, setprop and replaceby scripts
#

# discover BASEDIR
BASEDIR=`dirname "$0"`/.
BASEDIR=`(cd "$BASEDIR"; pwd)`
ls -l "$0" | grep -e '->' > /dev/null 2>&1
if [ $? = 0 ]; then
  #this is softlink
  _PWD=`pwd`
  _EXEDIR=`dirname "$0"`
  cd "$_EXEDIR"
  _BASENAME=`basename "$0"`
  _REALFILE=`ls -l "$_BASENAME" | sed 's/.*->\ //g'`
   BASEDIR=`dirname "$_REALFILE"`/..
   BASEDIR=`(cd "$BASEDIR"; pwd)`
   cd "$_PWD"
fi

if [ $# -eq 0 ]; then
    echo "Usage (long format): shconf {version|getprop|setprop|replaceby}"
    echo "Usage (short format): shconf {-v|-g|-s|-r}"
fi

# sub-command
while [ $# -gt 0 ]; do
  COMMAND=$1
  case $COMMAND in
    getprop|-g)
      shift 1
      exec sh $BASEDIR/getprop.sh "$@"
      break
      ;;
    setprop|-s)
      shift 1
      sh $BASEDIR/setprop.sh "$@"
      break
      ;;
    replaceby|-r)
      shift 1
      sh $BASEDIR/replaceby.sh "$@"
      break
      ;;
    version|-v)
      version=`sh $BASEDIR/getprop.sh version $BASEDIR/version`
      echo "shconf "$version
      break
      ;;
    ostype|-o)
      ostype=`sh $BASEDIR/ostype.sh`
      echo $ostype
      break
      ;;
    *)
      echo "command not supported"
      break
      ;;
  esac
done
